/* Generated by DBCC, see <https://github.com/howerj/dbcc> 
This file was generated by dbcc: See <https://github.com/howerj/dbcc>

Consider donating; see the repo for more information, this project 
requires your support to continue.

For those with paid support or to inquire about paid support
please Email <mailto:hello.operator.co.uk@gmail.com>.

*/

#include "dps_template.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x28a_DpsSlaveMexMode0(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* board_name: start-bit 8, length 56, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x28a_DpsSlaveMexMode0.board_name)) & 0xffffffffffffff;
	x <<= 8; 
	i |= x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28a_DpsSlaveMexMode0.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28a_DpsSlaveMexMode0.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	*data = (i);
	o->can_0x28a_DpsSlaveMexMode0_tx = 1;
	return 8;
}

static int unpack_can_0x28a_DpsSlaveMexMode0(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* board_name: start-bit 8, length 56, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xffffffffffffff;
	o->can_0x28a_DpsSlaveMexMode0.board_name = x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x28a_DpsSlaveMexMode0.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x28a_DpsSlaveMexMode0.board_id = x;
	o->can_0x28a_DpsSlaveMexMode0_rx = 1;
	o->can_0x28a_DpsSlaveMexMode0_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x28a_board_name(const can_obj_dps_template_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x28a_DpsSlaveMexMode0.board_name);
	*out = rval;
	return 0;
}

int encode_can_0x28a_board_name(can_obj_dps_template_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x28a_DpsSlaveMexMode0.board_name = in;
	return 0;
}

int decode_can_0x28a_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28a_DpsSlaveMexMode0.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x28a_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28a_DpsSlaveMexMode0.Mode = in;
	return 0;
}

int decode_can_0x28a_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28a_DpsSlaveMexMode0.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x28a_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28a_DpsSlaveMexMode0.board_id = in;
	return 0;
}

int print_can_0x28a_DpsSlaveMexMode0(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "board_name = (wire: %.0f)\n", (double)(o->can_0x28a_DpsSlaveMexMode0.board_name)));
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x28a_DpsSlaveMexMode0.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x28a_DpsSlaveMexMode0.board_id)));
	return r;
}

static int pack_can_0x28b_DpsSlaveMexMode1(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* var_name: start-bit 16, length 48, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x28b_DpsSlaveMexMode1.var_name)) & 0xffffffffffff;
	x <<= 16; 
	i |= x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28b_DpsSlaveMexMode1.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28b_DpsSlaveMexMode1.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28b_DpsSlaveMexMode1.var_id)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x28b_DpsSlaveMexMode1_tx = 1;
	return 8;
}

static int unpack_can_0x28b_DpsSlaveMexMode1(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* var_name: start-bit 16, length 48, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffffffffffff;
	o->can_0x28b_DpsSlaveMexMode1.var_name = x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x28b_DpsSlaveMexMode1.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x28b_DpsSlaveMexMode1.board_id = x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x28b_DpsSlaveMexMode1.var_id = x;
	o->can_0x28b_DpsSlaveMexMode1_rx = 1;
	o->can_0x28b_DpsSlaveMexMode1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x28b_var_name(const can_obj_dps_template_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x28b_DpsSlaveMexMode1.var_name);
	*out = rval;
	return 0;
}

int encode_can_0x28b_var_name(can_obj_dps_template_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x28b_DpsSlaveMexMode1.var_name = in;
	return 0;
}

int decode_can_0x28b_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28b_DpsSlaveMexMode1.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x28b_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28b_DpsSlaveMexMode1.Mode = in;
	return 0;
}

int decode_can_0x28b_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28b_DpsSlaveMexMode1.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x28b_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28b_DpsSlaveMexMode1.board_id = in;
	return 0;
}

int decode_can_0x28b_var_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28b_DpsSlaveMexMode1.var_id);
	*out = rval;
	return 0;
}

int encode_can_0x28b_var_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28b_DpsSlaveMexMode1.var_id = in;
	return 0;
}

int print_can_0x28b_DpsSlaveMexMode1(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "var_name = (wire: %.0f)\n", (double)(o->can_0x28b_DpsSlaveMexMode1.var_name)));
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x28b_DpsSlaveMexMode1.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x28b_DpsSlaveMexMode1.board_id)));
	r = print_helper(r, fprintf(output, "var_id = (wire: %.0f)\n", (double)(o->can_0x28b_DpsSlaveMexMode1.var_id)));
	return r;
}

static int pack_can_0x28c_DpsSlaveMexMode2(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28c_DpsSlaveMexMode2.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28c_DpsSlaveMexMode2.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28c_DpsSlaveMexMode2.var_id)) & 0xf;
	x <<= 8; 
	i |= x;
	/* type: start-bit 12, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28c_DpsSlaveMexMode2.type)) & 0x3;
	x <<= 12; 
	i |= x;
	/* size: start-bit 14, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28c_DpsSlaveMexMode2.size)) & 0x3;
	x <<= 14; 
	i |= x;
	*data = (i);
	o->can_0x28c_DpsSlaveMexMode2_tx = 1;
	return 8;
}

static int unpack_can_0x28c_DpsSlaveMexMode2(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x28c_DpsSlaveMexMode2.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x28c_DpsSlaveMexMode2.board_id = x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x28c_DpsSlaveMexMode2.var_id = x;
	/* type: start-bit 12, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 12) & 0x3;
	o->can_0x28c_DpsSlaveMexMode2.type = x;
	/* size: start-bit 14, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 14) & 0x3;
	o->can_0x28c_DpsSlaveMexMode2.size = x;
	o->can_0x28c_DpsSlaveMexMode2_rx = 1;
	o->can_0x28c_DpsSlaveMexMode2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x28c_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28c_DpsSlaveMexMode2.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x28c_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28c_DpsSlaveMexMode2.Mode = in;
	return 0;
}

int decode_can_0x28c_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28c_DpsSlaveMexMode2.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x28c_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28c_DpsSlaveMexMode2.board_id = in;
	return 0;
}

int decode_can_0x28c_var_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28c_DpsSlaveMexMode2.var_id);
	*out = rval;
	return 0;
}

int encode_can_0x28c_var_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28c_DpsSlaveMexMode2.var_id = in;
	return 0;
}

int decode_can_0x28c_type(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28c_DpsSlaveMexMode2.type);
	if (rval <= 2) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x28c_type(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28c_DpsSlaveMexMode2.type = 0;
	if (in > 2)
		return -1;
	o->can_0x28c_DpsSlaveMexMode2.type = in;
	return 0;
}

int decode_can_0x28c_size(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28c_DpsSlaveMexMode2.size);
	if (rval <= 2) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x28c_size(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28c_DpsSlaveMexMode2.size = 0;
	if (in > 2)
		return -1;
	o->can_0x28c_DpsSlaveMexMode2.size = in;
	return 0;
}

int print_can_0x28c_DpsSlaveMexMode2(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x28c_DpsSlaveMexMode2.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x28c_DpsSlaveMexMode2.board_id)));
	r = print_helper(r, fprintf(output, "var_id = (wire: %.0f)\n", (double)(o->can_0x28c_DpsSlaveMexMode2.var_id)));
	r = print_helper(r, fprintf(output, "type = (wire: %.0f)\n", (double)(o->can_0x28c_DpsSlaveMexMode2.type)));
	r = print_helper(r, fprintf(output, "size = (wire: %.0f)\n", (double)(o->can_0x28c_DpsSlaveMexMode2.size)));
	return r;
}

static int pack_can_0x28d_DpsSlaveMexMode3(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* value: start-bit 16, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x28d_DpsSlaveMexMode3.value)) & 0xffffffff;
	x <<= 16; 
	i |= x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28d_DpsSlaveMexMode3.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28d_DpsSlaveMexMode3.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x28d_DpsSlaveMexMode3.var_id)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x28d_DpsSlaveMexMode3_tx = 1;
	return 8;
}

static int unpack_can_0x28d_DpsSlaveMexMode3(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* value: start-bit 16, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffffffff;
	o->can_0x28d_DpsSlaveMexMode3.value = x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x28d_DpsSlaveMexMode3.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x28d_DpsSlaveMexMode3.board_id = x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x28d_DpsSlaveMexMode3.var_id = x;
	o->can_0x28d_DpsSlaveMexMode3_rx = 1;
	o->can_0x28d_DpsSlaveMexMode3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x28d_value(const can_obj_dps_template_h_t *o, uint32_t *out) {
	assert(o);
	assert(out);
	uint32_t rval = (uint32_t)(o->can_0x28d_DpsSlaveMexMode3.value);
	if (rval <= 2) {
		*out = rval;
		return 0;
	} else {
		*out = (uint32_t)0;
		return -1;
	}
}

int encode_can_0x28d_value(can_obj_dps_template_h_t *o, uint32_t in) {
	assert(o);
	o->can_0x28d_DpsSlaveMexMode3.value = 0;
	if (in > 2)
		return -1;
	o->can_0x28d_DpsSlaveMexMode3.value = in;
	return 0;
}

int decode_can_0x28d_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28d_DpsSlaveMexMode3.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x28d_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28d_DpsSlaveMexMode3.Mode = in;
	return 0;
}

int decode_can_0x28d_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28d_DpsSlaveMexMode3.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x28d_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28d_DpsSlaveMexMode3.board_id = in;
	return 0;
}

int decode_can_0x28d_var_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x28d_DpsSlaveMexMode3.var_id);
	*out = rval;
	return 0;
}

int encode_can_0x28d_var_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x28d_DpsSlaveMexMode3.var_id = in;
	return 0;
}

int print_can_0x28d_DpsSlaveMexMode3(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "value = (wire: %.0f)\n", (double)(o->can_0x28d_DpsSlaveMexMode3.value)));
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x28d_DpsSlaveMexMode3.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x28d_DpsSlaveMexMode3.board_id)));
	r = print_helper(r, fprintf(output, "var_id = (wire: %.0f)\n", (double)(o->can_0x28d_DpsSlaveMexMode3.var_id)));
	return r;
}

static int pack_can_0x294_DpsMasterMexMode0(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x294_DpsMasterMexMode0.Mode)) & 0xf;
	i |= x;
	/* reserved: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x294_DpsMasterMexMode0.reserved)) & 0x1;
	x <<= 4; 
	i |= x;
	*data = (i);
	o->can_0x294_DpsMasterMexMode0_tx = 1;
	return 8;
}

static int unpack_can_0x294_DpsMasterMexMode0(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x294_DpsMasterMexMode0.Mode = x;
	/* reserved: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->can_0x294_DpsMasterMexMode0.reserved = x;
	o->can_0x294_DpsMasterMexMode0_rx = 1;
	o->can_0x294_DpsMasterMexMode0_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x294_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x294_DpsMasterMexMode0.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x294_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x294_DpsMasterMexMode0.Mode = in;
	return 0;
}

int decode_can_0x294_reserved(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x294_DpsMasterMexMode0.reserved);
	*out = rval;
	return 0;
}

int encode_can_0x294_reserved(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x294_DpsMasterMexMode0.reserved = in;
	return 0;
}

int print_can_0x294_DpsMasterMexMode0(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x294_DpsMasterMexMode0.Mode)));
	r = print_helper(r, fprintf(output, "reserved = (wire: %.0f)\n", (double)(o->can_0x294_DpsMasterMexMode0.reserved)));
	return r;
}

static int pack_can_0x295_DpsMasterMexMode1(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x295_DpsMasterMexMode1.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x295_DpsMasterMexMode1.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	*data = (i);
	o->can_0x295_DpsMasterMexMode1_tx = 1;
	return 8;
}

static int unpack_can_0x295_DpsMasterMexMode1(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x295_DpsMasterMexMode1.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x295_DpsMasterMexMode1.board_id = x;
	o->can_0x295_DpsMasterMexMode1_rx = 1;
	o->can_0x295_DpsMasterMexMode1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x295_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x295_DpsMasterMexMode1.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x295_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x295_DpsMasterMexMode1.Mode = in;
	return 0;
}

int decode_can_0x295_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x295_DpsMasterMexMode1.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x295_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x295_DpsMasterMexMode1.board_id = in;
	return 0;
}

int print_can_0x295_DpsMasterMexMode1(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x295_DpsMasterMexMode1.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x295_DpsMasterMexMode1.board_id)));
	return r;
}

static int pack_can_0x296_DpsMasterMexMode2(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x296_DpsMasterMexMode2.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x296_DpsMasterMexMode2.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x296_DpsMasterMexMode2.var_id)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x296_DpsMasterMexMode2_tx = 1;
	return 8;
}

static int unpack_can_0x296_DpsMasterMexMode2(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x296_DpsMasterMexMode2.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x296_DpsMasterMexMode2.board_id = x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x296_DpsMasterMexMode2.var_id = x;
	o->can_0x296_DpsMasterMexMode2_rx = 1;
	o->can_0x296_DpsMasterMexMode2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x296_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x296_DpsMasterMexMode2.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x296_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x296_DpsMasterMexMode2.Mode = in;
	return 0;
}

int decode_can_0x296_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x296_DpsMasterMexMode2.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x296_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x296_DpsMasterMexMode2.board_id = in;
	return 0;
}

int decode_can_0x296_var_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x296_DpsMasterMexMode2.var_id);
	*out = rval;
	return 0;
}

int encode_can_0x296_var_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x296_DpsMasterMexMode2.var_id = in;
	return 0;
}

int print_can_0x296_DpsMasterMexMode2(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x296_DpsMasterMexMode2.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x296_DpsMasterMexMode2.board_id)));
	r = print_helper(r, fprintf(output, "var_id = (wire: %.0f)\n", (double)(o->can_0x296_DpsMasterMexMode2.var_id)));
	return r;
}

static int pack_can_0x297_DpsMasterMexMode3(can_obj_dps_template_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* value: start-bit 16, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32_t)(o->can_0x297_DpsMasterMexMode3.value)) & 0xffffffff;
	x <<= 16; 
	i |= x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x297_DpsMasterMexMode3.Mode)) & 0xf;
	i |= x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x297_DpsMasterMexMode3.board_id)) & 0xf;
	x <<= 4; 
	i |= x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x297_DpsMasterMexMode3.var_id)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x297_DpsMasterMexMode3_tx = 1;
	return 8;
}

static int unpack_can_0x297_DpsMasterMexMode3(can_obj_dps_template_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* value: start-bit 16, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffffffff;
	o->can_0x297_DpsMasterMexMode3.value = x;
	/* Mode: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x297_DpsMasterMexMode3.Mode = x;
	/* board_id: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x297_DpsMasterMexMode3.board_id = x;
	/* var_id: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x297_DpsMasterMexMode3.var_id = x;
	o->can_0x297_DpsMasterMexMode3_rx = 1;
	o->can_0x297_DpsMasterMexMode3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x297_value(const can_obj_dps_template_h_t *o, uint32_t *out) {
	assert(o);
	assert(out);
	uint32_t rval = (uint32_t)(o->can_0x297_DpsMasterMexMode3.value);
	*out = rval;
	return 0;
}

int encode_can_0x297_value(can_obj_dps_template_h_t *o, uint32_t in) {
	assert(o);
	o->can_0x297_DpsMasterMexMode3.value = in;
	return 0;
}

int decode_can_0x297_Mode(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x297_DpsMasterMexMode3.Mode);
	*out = rval;
	return 0;
}

int encode_can_0x297_Mode(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x297_DpsMasterMexMode3.Mode = in;
	return 0;
}

int decode_can_0x297_board_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x297_DpsMasterMexMode3.board_id);
	*out = rval;
	return 0;
}

int encode_can_0x297_board_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x297_DpsMasterMexMode3.board_id = in;
	return 0;
}

int decode_can_0x297_var_id(const can_obj_dps_template_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x297_DpsMasterMexMode3.var_id);
	*out = rval;
	return 0;
}

int encode_can_0x297_var_id(can_obj_dps_template_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x297_DpsMasterMexMode3.var_id = in;
	return 0;
}

int print_can_0x297_DpsMasterMexMode3(const can_obj_dps_template_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "value = (wire: %.0f)\n", (double)(o->can_0x297_DpsMasterMexMode3.value)));
	r = print_helper(r, fprintf(output, "Mode = (wire: %.0f)\n", (double)(o->can_0x297_DpsMasterMexMode3.Mode)));
	r = print_helper(r, fprintf(output, "board_id = (wire: %.0f)\n", (double)(o->can_0x297_DpsMasterMexMode3.board_id)));
	r = print_helper(r, fprintf(output, "var_id = (wire: %.0f)\n", (double)(o->can_0x297_DpsMasterMexMode3.var_id)));
	return r;
}

int unpack_message(can_obj_dps_template_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x28a: return unpack_can_0x28a_DpsSlaveMexMode0(o, data, dlc, time_stamp);
	case 0x28b: return unpack_can_0x28b_DpsSlaveMexMode1(o, data, dlc, time_stamp);
	case 0x28c: return unpack_can_0x28c_DpsSlaveMexMode2(o, data, dlc, time_stamp);
	case 0x28d: return unpack_can_0x28d_DpsSlaveMexMode3(o, data, dlc, time_stamp);
	case 0x294: return unpack_can_0x294_DpsMasterMexMode0(o, data, dlc, time_stamp);
	case 0x295: return unpack_can_0x295_DpsMasterMexMode1(o, data, dlc, time_stamp);
	case 0x296: return unpack_can_0x296_DpsMasterMexMode2(o, data, dlc, time_stamp);
	case 0x297: return unpack_can_0x297_DpsMasterMexMode3(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_dps_template_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x28a: return pack_can_0x28a_DpsSlaveMexMode0(o, data);
	case 0x28b: return pack_can_0x28b_DpsSlaveMexMode1(o, data);
	case 0x28c: return pack_can_0x28c_DpsSlaveMexMode2(o, data);
	case 0x28d: return pack_can_0x28d_DpsSlaveMexMode3(o, data);
	case 0x294: return pack_can_0x294_DpsMasterMexMode0(o, data);
	case 0x295: return pack_can_0x295_DpsMasterMexMode1(o, data);
	case 0x296: return pack_can_0x296_DpsMasterMexMode2(o, data);
	case 0x297: return pack_can_0x297_DpsMasterMexMode3(o, data);
	default: break; 
	}
	return -1; 
}

int message_dlc(const unsigned long id) {
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x28a: return 8;
	case 0x28b: return 8;
	case 0x28c: return 8;
	case 0x28d: return 8;
	case 0x294: return 8;
	case 0x295: return 8;
	case 0x296: return 8;
	case 0x297: return 8;
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_dps_template_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x28a: return print_can_0x28a_DpsSlaveMexMode0(o, output);
	case 0x28b: return print_can_0x28b_DpsSlaveMexMode1(o, output);
	case 0x28c: return print_can_0x28c_DpsSlaveMexMode2(o, output);
	case 0x28d: return print_can_0x28d_DpsSlaveMexMode3(o, output);
	case 0x294: return print_can_0x294_DpsMasterMexMode0(o, output);
	case 0x295: return print_can_0x295_DpsMasterMexMode1(o, output);
	case 0x296: return print_can_0x296_DpsMasterMexMode2(o, output);
	case 0x297: return print_can_0x297_DpsMasterMexMode3(o, output);
	default: break; 
	}
	return -1; 
}

